-- Tabloların oluşturulması

-- 1. Departments
CREATE TABLE Departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(100) NOT NULL,
    location VARCHAR2(100)
);

-- 2. Doctors
CREATE TABLE Doctors (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    specialization VARCHAR2(100),
    contact_number VARCHAR2(20),
    email VARCHAR2(100),
    department_id NUMBER
);

-- 3. Patients
CREATE TABLE Patients (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR2(10),
    contact_number VARCHAR2(20),
    address VARCHAR2(200)
);

-- 4. Appointments
CREATE TABLE Appointments (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time VARCHAR2(10),
    status VARCHAR2(20)
);

-- 5. Medications
CREATE TABLE Medications (
    medication_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(200),
    dosage VARCHAR2(50)
);

-- 6. Prescriptions
CREATE TABLE Prescriptions (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    issued_date DATE DEFAULT SYSDATE
);

-- 7. Prescription_Details
CREATE TABLE Prescription_Details (
    prescription_id NUMBER NOT NULL,
    medication_id NUMBER NOT NULL,
    quantity NUMBER,
    instructions VARCHAR2(200),
    PRIMARY KEY (prescription_id, medication_id)
);

-- 8. Medical_Records
CREATE TABLE Medical_Records (
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER,
    diagnosis VARCHAR2(200),
    treatment VARCHAR2(200),
    record_date DATE DEFAULT SYSDATE
);

-- 9. Rooms
CREATE TABLE Rooms (
    room_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type VARCHAR2(50),
    capacity NUMBER
);

-- 10. Admissions
CREATE TABLE Admissions (
    admission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    room_id NUMBER NOT NULL,
    admission_date DATE NOT NULL,
    discharge_date DATE
);

-- 11. Admission_Log
CREATE TABLE Admission_Log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id NUMBER NOT NULL,
    log_message VARCHAR2(200),
    log_date DATE DEFAULT SYSDATE
);

-- 12. Payments
CREATE TABLE Payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    amount NUMBER(10,2),
    payment_date DATE DEFAULT SYSDATE
);
